/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const STATIC_QUOTES = [
  "The secret of getting ahead is getting started. – Mark Twain",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
  "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Your talent determines what you can do. Your motivation determines how much you are willing to do. – Lou Holtz",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "I am not a product of my circumstances. I am a product of my decisions. – Stephen Covey",
  "Every child is an artist. The problem is how to remain an artist once he grows up. – Pablo Picasso",
  "You can never cross the ocean until you have the courage to lose sight of the shore. – Christopher Columbus",
  "Either you run the day, or the day runs you. – Jim Rohn",
  "Whether you think you can or you think you can’t, you’re right. – Henry Ford",
  "The two most important days in your life are the day you are born and the day you find out why. – Mark Twain",
  "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it. – Johann Wolfgang von Goethe",
  "The best revenge is massive success. – Frank Sinatra",
  "People often say that motivation doesn’t last. Well, neither does bathing. That’s why we recommend it daily. – Zig Ziglar",
  "Life shrinks or expands in proportion to one's courage. – Anais Nin",
  "If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced. – Vincent Van Gogh",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing. – Aristotle",
  "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you. – Jesus",
  "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
  "Go confidently in the direction of your dreams. Live the life you have imagined. – Henry David Thoreau",
  "Everything has beauty, but not everyone can see. – Confucius",
  "When I let go of what I am, I become what I might be. – Lao Tzu",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away. – Maya Angelou",
  "Happiness is not something readymade. It comes from your own actions. – Dalai Lama",
  "If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on. – Sheryl Sandberg",
  "Everything should be made as simple as possible, but not simpler. – Albert Einstein",
  "The question isn’t who is going to let me; it’s who is going to stop me. – Ayn Rand",
  "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
  "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do. – Leonardo da Vinci",
  "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless. – Jamie Paolinetti",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. – Eleanor Roosevelt",
  "The mind is everything. What you think you become. – Buddha",
  "An unexamined life is not worth living. – Socrates",
  "Your time is limited, so don't waste it living someone else's life. – Steve Jobs",
  "Winning isn't everything, but wanting to win is. – Vince Lombardi",
  "I am not a product of my circumstances. I am a product of my decisions. – Stephen Covey",
  "You miss 100% of the shots you don't take. – Wayne Gretzky",
  "I’ve missed more than 9000 shots in my career. I've lost almost 300 games. 26 times, I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed. – Michael Jordan",
  "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
  "It’s not the years in your life that count. It’s the life in your years. – Abraham Lincoln",
  "Change your thoughts and you change your world. – Norman Vincent Peale",
  "Either write something worth reading or do something worth writing. – Benjamin Franklin",
  "Nothing is impossible, the word itself says, “I’m possible!” – Audrey Hepburn",
  "Everything is figureoutable. – Marie Forleo",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "Whatever the mind of man can conceive and believe, it can achieve. – Napoleon Hill",
  "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
  "Creativity is intelligence having fun. – Albert Einstein",
  "Do what you can, with what you have, where you are. – Theodore Roosevelt",
  "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better. – Samuel Beckett",
  "Happiness is a butterfly, which when pursued, is always just beyond your grasp, but which, if you will sit down quietly, may alight upon you. – Nathaniel Hawthorne",
  "If you can’t explain it simply, you don’t understand it well enough. – Albert Einstein",
  "You must be the change you wish to see in the world. – Mahatma Gandhi",
  "The only thing we have to fear is fear itself. – Franklin D. Roosevelt",
  "Do one thing every day that scares you. – Eleanor Roosevelt",
  "Dream big and dare to fail. – Norman Vaughan",
  "What you do speaks so loudly that I cannot hear what you say. – Ralph Waldo Emerson",
  "Tough times never last, but tough people do. – Robert H. Schuller",
  "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
  "If you want to achieve greatness stop asking for permission. – Unknown",
  "Things work out best for those who make the best of how things work out. – John Wooden",
  "To live a creative life, we must lose our fear of being wrong. – Unknown",
  "If you are not willing to risk the usual you will have to settle for the ordinary. – Jim Rohn",
  "Trust because you are willing to accept the risk, not because it's safe or certain. – Unknown",
  "Take up one idea. Make that one idea your life--think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. – Swami Vivekananda",
  "All our dreams can come true if we have the courage to pursue them. – Walt Disney",
  "Good things come to people who wait, but better things come to those who go out and get them. – Unknown",
  "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "Just when the caterpillar thought the world was ending, he turned into a butterfly. – Proverb",
  "Successful entrepreneurs are givers and not takers of positive energy. – Unknown",
  "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them. – Vaibhav Shah",
  "Opportunities don't happen, you create them. – Chris Grosser",
  "Try not to become a person of success, but rather try to become a person of value. – Albert Einstein",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. – Eleanor Roosevelt",
  "I have not failed. I've just found 10,000 ways that won't work. – Thomas Edison",
  "If you don't value your time, neither will others. Stop giving away your time and talents--start charging for it. – Kim Garst",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. – David Brinkley",
  "No one can make you feel inferior without your consent. – Eleanor Roosevelt",
  "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. – Henry Ford",
  "If you're going through hell, keep going. – Winston Churchill",
  "The ones who are crazy enough to think they can change the world are the ones who do. – Steve Jobs",
  "Don't raise your voice, improve your argument. – Desmond Tutu",
  "What seems to us as bitter trials are often blessings in disguise. – Oscar Wilde",
  "The meaning of life is to find your gift. The purpose of life is to give it away. – Anonymous",
  "The distance between insanity and genius is measured only by success. – Bruce Feirstein",
  "When you stop chasing the wrong things, you give the right things a chance to catch you. – Lolly Daskal",
  "I believe that the only courage anybody ever needs is the courage to follow your own dreams. – Oprah Winfrey",
  "No masterpiece was ever created by a lazy artist. – Anonymous",
  "Happiness is not something you postpone for the future; it is something you design for the present. – Jim Rohn",
  "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. – Thomas J. Watson",
  "The starting point of all achievement is desire. – Napoleon Hill",
  "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it. – Anonymous",
  "Your problem isn't the problem. Your reaction is the problem. – Anonymous",
  "You can do anything, but not everything. – Anonymous",
  "Innovation distinguishes between a leader and a follower. – Steve Jobs",
  "Focus on being productive instead of busy. – Tim Ferriss",
  "It’s not what you look at that matters, it’s what you see. – Henry David Thoreau",
  "The path to success is to take massive, determined action. – Tony Robbins",
  "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
  "A goal is a dream with a deadline. – Napoleon Hill",
  "Your life only gets better when you get better. – Brian Tracy",
  "Don't count the days, make the days count. – Muhammad Ali",
  "Progress is stayin' hungry. – Tony Robbins",
  "The quality of your life is the quality of your relationships. – Tony Robbins",
  "If you do what you've always done, you'll get what you've always gotten. – Tony Robbins",
  "It is in your moments of decision that your destiny is shaped. – Tony Robbins",
  "The only thing that's keeping you from getting what you want is the story you keep telling yourself. – Tony Robbins",
  "Demand more from yourself than anyone else could ever expect. – Tony Robbins",
  "Change is inevitable. Progress is optional. – Tony Robbins",
  "Where focus goes, energy flows. – Tony Robbins",
  "Mastery takes time. – Anonymous",
  "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
  "Action is the foundational key to all success. – Pablo Picasso",
  "Discipline is the bridge between goals and accomplishment. – Jim Rohn",
  "Motivation is what gets you started. Habit is what keeps you going. – Jim Rohn",
  "Success is nothing more than a few simple disciplines, practiced every day. – Jim Rohn",
  "Work harder on yourself than you do on your job. – Jim Rohn",
  "Don't wish it were easier, wish you were better. – Jim Rohn",
  "If you are not growing, you are dying. – Tony Robbins"
];
